# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-task" do
  version "3.53.1"

  on_macos do
    on_intel do
      sha256 "7f1a702d54a789cb818a636039a83df071f4179893133afafa4eba351a7e19ef"
      url "https://github.com/go-task/task/releases/download/v#{version}/task_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "85d2d96c2380b33d7855b07b3f7a20dc7ca0eda999a26efa0fb5f6f32b366cd7"
      url "https://github.com/go-task/task/releases/download/v#{version}/task_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a54a408f6861ff921f6e87774180db31bacd8c1e7c944ca696db9fea49a82fc7"
      url "https://github.com/go-task/task/releases/download/v#{version}/task_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e3ad19101493a0112e1f22ae8ccc54bf03e533b1076a0ca1e6c782a09ad2e588"
      url "https://github.com/go-task/task/releases/download/v#{version}/task_linux_arm64.tar.gz"
    end
  end

  name "go-task"
  desc "A fast, cross-platform build tool inspired by Make, designed for modern workflows."
  homepage "https://taskfile.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "task"
  bash_completion "completion/bash/task.bash"
  fish_completion "completion/fish/task.fish"
  zsh_completion "completion/zsh/_task"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/task"]
    end
  end

  # No zap stanza required

end
