# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-task@3.54" do
  version "3.54.0"

  on_macos do
    on_arm do
      sha256 "12a69fcf37bb8d5bc9150c44f9a936775b73e59ff044c2c245232f198c135637"
      url "https://github.com/go-task/task/releases/download/v#{version}/task_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0543b0844a725814c0412d3f4bed12873ce9ed0da207b15775f63a97d734aac0"
      url "https://github.com/go-task/task/releases/download/v#{version}/task_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d7189d439d4a6058e39e1b2acd7c8b27acd4856691b408f23b242e4294e1df5b"
      url "https://github.com/go-task/task/releases/download/v#{version}/task_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "680859dbb4d881a9c72d4d9a8f510825450849af8567deacd7302c01124416fb"
      url "https://github.com/go-task/task/releases/download/v#{version}/task_linux_amd64.tar.gz"
    end
  end

  name "go-task@3.54"
  desc "A fast, cross-platform build tool inspired by Make, designed for modern workflows."
  homepage "https://taskfile.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "task"
  bash_completion "completion/bash/task.bash"
  fish_completion "completion/fish/task.fish"
  zsh_completion "completion/zsh/_task"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/task"]
    end
  end

  # No zap stanza required
end
