# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoTask < Formula
  desc "Task runner / simpler Make alternative written in Go"
  homepage "https://taskfile.dev"
  version "3.42.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-task/task/releases/download/v3.42.1/task_darwin_amd64.tar.gz"
      sha256 "07073067fc3312d5f6cb3a24a496ec49aaa978dbdcfa7b5cdb694840c78440bd"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-task/task/releases/download/v3.42.1/task_darwin_arm64.tar.gz"
      sha256 "69aab5d044ff5a0de4ead58a565cd4953ede821dc5c56b9b868a3866f622eba0"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-task/task/releases/download/v3.42.1/task_linux_amd64.tar.gz"
        sha256 "05b41f97e655f56cc8a7617106622dbfb5f647d13ec6013ff7719bc80b52746c"

        def install
          bin.install "task"
          bash_completion.install "completion/bash/task.bash" => "task"
          zsh_completion.install "completion/zsh/_task" => "_task"
          fish_completion.install "completion/fish/task.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/go-task/task/releases/download/v3.42.1/task_linux_arm.tar.gz"
        sha256 "c0e90897947a945dd685c570238f5b633b2f102d3dd8f098f9db6545e05b67a5"

        def install
          bin.install "task"
          bash_completion.install "completion/bash/task.bash" => "task"
          zsh_completion.install "completion/zsh/_task" => "_task"
          fish_completion.install "completion/fish/task.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-task/task/releases/download/v3.42.1/task_linux_arm64.tar.gz"
        sha256 "3019dd489ec70a56498ceb919aca06ff46ccf8e7fdd0c99913c9bb27dbd7a44d"

        def install
          bin.install "task"
          bash_completion.install "completion/bash/task.bash" => "task"
          zsh_completion.install "completion/zsh/_task" => "_task"
          fish_completion.install "completion/fish/task.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/task", "--help"
  end
end
