# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoTask < Formula
  desc "Task runner / simpler Make alternative written in Go"
  homepage "https://taskfile.dev"
  version "3.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/go-task/task/releases/download/v3.11.0/task_darwin_arm64.tar.gz"
      sha256 "fd90544509844bf5de07cbbb7209e9346473572281a471126cebf11611180ad3"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-task/task/releases/download/v3.11.0/task_darwin_amd64.tar.gz"
      sha256 "4c35c6a5236609bb275b7dd5dcd2162a004c80f1f0a97d7db27d5cffd99af5b9"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/go-task/task/releases/download/v3.11.0/task_linux_amd64.tar.gz"
      sha256 "8284fa89367e0bbb8ba5dcb90baa6826b7669c4a317e5b9a46711f7380075e21"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/go-task/task/releases/download/v3.11.0/task_linux_arm.tar.gz"
      sha256 "67a10f75b21348b5d28b2f58cf7bb798a9b28e816c52d5a7213713e26a5aaab2"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-task/task/releases/download/v3.11.0/task_linux_arm64.tar.gz"
      sha256 "a5b90d84ee5a2d6132634c3c922e7d9ac082ba9211e3adc96c00ff70f2c6a16d"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
  end

  test do
    system "#{bin}/task", "--help"
  end
end
