# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoTask < Formula
  desc "Task runner / simpler Make alternative written in Go"
  homepage "https://taskfile.dev"
  version "3.16.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/go-task/task/releases/download/v3.16.0/task_darwin_arm64.tar.gz"
      sha256 "b6d851947057decc38236224fe0723da2bb51cd00bad65a29a1ffecf7a5df539"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-task/task/releases/download/v3.16.0/task_darwin_amd64.tar.gz"
      sha256 "0c56167fd9af86cffd4619ab26c476df26f4583354f6248a3348442347a04543"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/go-task/task/releases/download/v3.16.0/task_linux_arm.tar.gz"
      sha256 "9ca0d73d6a3bae54b22f33b97980c7dbacb6e65868cb44801b5bfeaaacaa708c"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-task/task/releases/download/v3.16.0/task_linux_amd64.tar.gz"
      sha256 "e928c2b753aee89c03b42a6b38b05043197f2e5ab1c956841357edc924633cc9"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-task/task/releases/download/v3.16.0/task_linux_arm64.tar.gz"
      sha256 "b4d8035533369fc186f2db3708c9d10354d93281868c253a8324e548cd258d29"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
  end

  test do
    system "#{bin}/task", "--help"
  end
end
